FROM eclipse-temurin:21-jre-alpine AS production

RUN apk add --no-cache curl

WORKDIR /app

COPY build/libs/*.jar /app/app.jar

ENV SPRING_PROFILES_ACTIVE=prod
ENV SERVER_PORT=8080

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar"]
